version: '3'


services:
  es:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    environment:
      - discovery.type=single-node
    privileged: true